"""add competitor_visibility and scoring llm tracking

Revision ID: 6d93a4ea9f49
Revises: ed1e9a9f6cfb
Create Date: 2026-07-08 01:23:05.393434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d93a4ea9f49'
down_revision = 'ed1e9a9f6cfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discovered_queries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('competitor_visibility', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('scoring_llm_provider', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('scoring_llm_model', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discovered_queries', schema=None) as batch_op:
        batch_op.drop_column('scoring_llm_model')
        batch_op.drop_column('scoring_llm_provider')
        batch_op.drop_column('competitor_visibility')

    # ### end Alembic commands ###
