"""add confidence_reasoning to discovered_queries

Revision ID: ed1e9a9f6cfb
Revises: ef438e780d10
Create Date: 2026-07-08 00:29:20.404906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed1e9a9f6cfb'
down_revision = 'ef438e780d10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discovered_queries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confidence_reasoning', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discovered_queries', schema=None) as batch_op:
        batch_op.drop_column('confidence_reasoning')

    # ### end Alembic commands ###
